[inputs]
# input directory with the files
dir = "inputs"

[inputs.res_profile]
# input files for data
list_of_files = "list_of_files_to_scale.csv"

[inputs.target_values]
header_row        = 1
year_column_key   = "year"

[outputs]
dir = "outputs"
display_plot = false
first_hour_to_plot = 2190
last_hour_to_plot = 2358